site_name: DS Tech Blog - mkdocs test
theme:
  name: material
  
plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.admonition # This is the specific one for [!type]  
  
  
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  